# vim: ft=dosini
[Metadata]
Name=Catppuccin Latte Teal
Version=2.0
Author=justTOBBI, Isabelinc, Kurome (modified)
Description=Catppuccin Latte Teal - Glassmorphism Style
ScaleWithDPI=True

[InputPanel]
Font=Maple Mono NF CN 14
Spacing=5

# Unselected candidate text color
NormalColor=#4c4f69
# Selected candidate text color
HighlightCandidateColor=#eff1f5
# Input (preedit) text color
HighlightColor=#179299
# Input (preedit) background color
HighlightBackgroundColor=#dce0e8

[InputPanel/TextMargin]
Left=20
Right=20
Top=12
Bottom=12

[InputPanel/Background]
# Use SVG for rounded corners + shadow
Image=panel.svg

[InputPanel/Background/Margin]
Left=12
Right=12
Top=12
Bottom=12

[InputPanel/Highlight]
# Use SVG for rounded highlight
Image=highlight.svg

[InputPanel/Highlight/Margin]
Left=20
Right=20
Top=12
Bottom=12

[Menu]
Font=Maple Mono NF CN 11
NormalColor=#4c4f69
Spacing=4

[Menu/Background]
Image=panel.svg

[Menu/Background/Margin]
Left=12
Right=12
Top=12
Bottom=12

[Menu/ContentMargin]
Left=4
Right=4
Top=4
Bottom=4

[Menu/Highlight]
Color=#179299

[Menu/Highlight/Margin]
Left=12
Right=12
Top=6
Bottom=6

[Menu/Separator]
Color=#e6e9ef

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/TextMargin]
Left=8
Right=8
Top=6
Bottom=6
